services:
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    environment:
      - PORT=3333

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
